<?xml version="1.0" encoding="UTF-8" standalone="no"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sch="http://soapservice.com/example" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://soapservice.com/example" targetNamespace="http://soapservice.com/example">
  <wsdl:types>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://soapservice.com/example">

    <xs:element name="sayHelloRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="text" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="sayHelloResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="text" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="sayHelloRequest">
    <wsdl:part element="tns:sayHelloRequest" name="sayHelloRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sayHelloResponse">
    <wsdl:part element="tns:sayHelloResponse" name="sayHelloResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="HelloPort">
    <wsdl:operation name="sayHello">
      <wsdl:input message="tns:sayHelloRequest" name="sayHelloRequest">
    </wsdl:input>
      <wsdl:output message="tns:sayHelloResponse" name="sayHelloResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HelloPortSoap11" type="tns:HelloPort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sayHello">
      <soap:operation soapAction=""/>
      <wsdl:input name="sayHelloRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sayHelloResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HelloPortService">
    <wsdl:port binding="tns:HelloPortSoap11" name="HelloPortSoap11">
      <soap:address location="http://localhost:8081/ws"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>