version: '3'
services:
  camel-hub-service:
    build: ./camel-hub-service
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - rest-service
      - soap-service
    networks:
      hub-network:
        ipv4_address: 10.5.0.2
  rest-service:
    build: ./rest-service
    restart: always
    ports:
      - "8082:8082"
    networks:
      hub-network:
        ipv4_address: 10.5.0.3
  soap-service:
    build: ./soap-service
    restart: always
    ports:
      - "8081:8081"
    networks:
      hub-network:
        ipv4_address: 10.5.0.4
networks:
  hub-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1